### ISSUE TITLE
PRECONDITION_FAILED handling when queue is set to AutoDelete

### ISSUE THREAD

**Issue by JamesIrish** [R-Suite/ServiceConnect-CSharp#20]
When a queue is marked as AutoDelete and the message bus is not disposed of correctly (i.e. application crashes etc.) then a subsequent connection attempt to the same queue (with identical settings) results in the following exception:

```C#
RabbitMQ.Client.Exceptions.AlreadyClosedException: Already closed: The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=406, text="PRECONDITION_FAILED - parameters for queue 'Ruffer.Research.Outlook.Addin-RUFFER-C16Q85J-hidadam' in vhost '/' not equivalent", classId=50, methodId=10, cause=
   at RabbitMQ.Client.Impl.SessionBase.Transmit(Command cmd)
   at RabbitMQ.Client.Impl.ModelBase.ModelRpc(MethodBase method, ContentHeaderBase header, Byte[] body)
   at RabbitMQ.Client.Framing.Impl.Model._Private_QueueBind(String queue, String exchange, String routingKey, Boolean nowait, IDictionary`2 arguments)
   at RabbitMQ.Client.Impl.ModelBase.QueueBind(String queue, String exchange, String routingKey, IDictionary`2 arguments)
   at R.MessageBus.Client.RabbitMQ.Consumer.CreateConsumer()
   at R.MessageBus.Client.RabbitMQ.Consumer.StartConsuming(ConsumerEventHandler messageReceived, String queueName, Nullable`1 exclusive, Nullable`1 autoDelete)
   at R.MessageBus.Core.ConsumerPool.<>c__DisplayClass1.<AddConsumer>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

The only option is to then manually delete the queue from RabbitMQ.   This is not ideal in a production environment.   Can this exception be caught and queue deleted beforehand (only when AutoDelete=true).

Thanks

**Comment by JamesIrish** [comment]
Nevermind RabbitMq client makes admin like this rather easy e.g.

```C#
var factory = new ConnectionFactory { Uri = string.Format("amqp://guest:guest@{0}:5672", queueServer) };
var conn = factory.CreateConnection();
var model = conn.CreateModel();
model.QueueDelete(queueName);
model.Close();
model.Dispose();
conn.Close();
conn.Dispose();
```
